backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "family"
    label: "Family Members"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Spouse", name: "spouse", widget: "string", required: false}
      - {label: "Children (List)", name: "children", widget: "list", field: {label: "Child Name", name: "child", widget: "string"}}
      - {label: "Biography", name: "body", widget: "markdown"}
