backend:
  name: git-gateway
  branch: main
media_folder: "static/images"
public_folder: "images"
collections:
  - name: "family"
    label: "Family Member"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Relation", name: "relation", widget: "string"}
      - {label: "Father Name", name: "father", widget: "string", required: false}
      - {label: "Mother Name", name: "mother", widget: "string", required: false}
      - {label: "Spouse Name", name: "spouse", widget: "string", required: false}
      - {label: "Siblings", name: "siblings", widget: "list", required: false}
